# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(403, 331)
        Downloader.setStyleSheet("QMainWindow{\n"
# "    background-color: rgb(64, 64, 64);\n"
# "    background-image:url(C:/Users/grezhdierud/PycharmProjects/PyQt5_downloader/logo1.png);\n"
# "    background-repeat: no-repeat;\n"
# "    background-position: center;\n"                                 
"    color: white;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Downloader)
        self.centralwidget.setStyleSheet("QWidget{\n"
# "    background-color: rgb(84, 78, 76);\n"
"    color: white;    \n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 381, 191))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 210, 381, 31))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 250, 381, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid black;\n"
"    background-color: #444444;\n"
"    color: white;    \n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 290, 381, 51))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid white;\n"
"    background-color: #444444;\n"
"    color: white;    \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        Downloader.setCentralWidget(self.centralwidget)

        self.retranslateUi(Downloader)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "MainWindow"))
        self.lineEdit.setText(_translate("Downloader", "http://www.youtube.com/Video"))
        self.pushButton.setText(_translate("Downloader", "Скачать"))
        self.pushButton_2.setText(_translate("Downloader", "Выбрать папку для сохранения"))
