# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Downloader-1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(800, 600)
        Downloader.setAutoFillBackground(False)
        Downloader.setStyleSheet("#Downloader{background-image:url(./im1.png)}")
        self.centralwidget = QtWidgets.QWidget(Downloader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
#         self.centralwidget.setStyleSheet("QWidget{\n"
# "    background-color: rgb(84, 78, 76);\n"
# "    color: white;    \n"
# "}")
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 421, 191))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 440, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 490, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid black;\n"
"    background-color: #444444;\n"
"    color: white;    \n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 540, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid white;\n"
"    background-color: #444444;\n"
"    color: white;    \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(280, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 210, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        Downloader.setCentralWidget(self.centralwidget)

        self.retranslateUi(Downloader)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "MainWindow"))
        self.lineEdit.setText(_translate("Downloader", "http://www.youtube.com/Video"))
        self.pushButton.setText(_translate("Downloader", "Скачать видео"))
        self.pushButton_2.setText(_translate("Downloader", "Выбрать папку для сохранения"))
        self.label.setText(_translate("Downloader", "Выберите качество скачивания"))
