# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Downloader-1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Downloader(object):
    def setupUi(self, Downloader):
        Downloader.setObjectName("Downloader")
        Downloader.resize(800, 600)
        Downloader.setAutoFillBackground(False)
#         Downloader.setStyleSheet("QMainWindow{\n"
# "    background-image:url(./images/Background(900x600).png)\n"
# "}\n"
# "")
        self.centralwidget = QtWidgets.QWidget(Downloader)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 421, 191))
        self.plainTextEdit.setStyleSheet("QPlainTextEdit{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 390, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 490, 421, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid black;\n"
"    background-color: #444444;\n"
"    color: white;    \n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 540, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(68, 68, 68);\n"
"    color: white;    \n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 2px solid white;\n"
"    background-color: #444444;\n"
"    color: white;    \n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 210, 421, 171))
        self.frame.setStyleSheet("QFrame{\n"
"    border: 2px solid #A4004D;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(220, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QСomboBox{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;\n"
"}")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 130, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(10, 130, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 70, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    border: 2px solid #A4004D;\n"
"    background-color: rgb(64, 64, 64);\n"
"    color: white;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 100, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setChecked(True)
        self.checkBox_4.setObjectName("checkBox_4")
        Downloader.setCentralWidget(self.centralwidget)

        self.retranslateUi(Downloader)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Downloader)

    def retranslateUi(self, Downloader):
        _translate = QtCore.QCoreApplication.translate
        Downloader.setWindowTitle(_translate("Downloader", "MainWindow"))
        self.lineEdit.setText(_translate("Downloader", "http://www.youtube.com/Video (Ссылка на ваше видео)"))
        self.pushButton.setText(_translate("Downloader", "Скачать "))
        self.pushButton_2.setText(_translate("Downloader", "Выбрать папку для сохранения"))
        self.checkBox_3.setText(_translate("Downloader", "Скачать только аудио дорожку"))
        self.lineEdit_2.setText(_translate("Downloader", "http://100.100.1.100:1000"))
        self.checkBox.setText(_translate("Downloader", "Использовать прокси?"))
        self.checkBox_2.setText(_translate("Downloader", "Скачать с субтитрами (при наличии)"))
        self.label.setText(_translate("Downloader", "Выберите качество скачивания"))
        self.checkBox_4.setText(_translate("Downloader", "Не скачивать весь плейлист"))
